PROG=xvcpi_modern
CFLAGS=-O3 -Wall -Wextra
LIBS=-lgpiod

all: $(PROG)

$(PROG): $(PROG).o
	$(CC) -o $(PROG) $< $(LIBS)

$(PROG).o: $(PROG).c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f $(PROG) *.o

install: $(PROG)
	sudo cp $(PROG) /usr/local/bin/
	sudo chmod +s /usr/local/bin/$(PROG)

uninstall:
	sudo rm -f /usr/local/bin/$(PROG)

.PHONY: all clean install uninstall
